# Generated by Django 5.1.7 on 2025-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_options_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, choices=[('A', 'Classroom A'), ('B', 'Classroom B'), ('C', 'Classroom C')], max_length=100, null=True),
        ),
    ]
