# Generated by Django 5.1.7 on 2025-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_student_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(default='Room 101', max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
