# Generated by Django 5.1.7 on 2025-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_classroom_options_remove_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
