# Generated by Django 5.1.7 on 2025-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_classroom_teacher_alter_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, choices=[('A', 'Classroom A'), ('B', 'Classroom B'), ('C', 'Classroom C')], max_length=100, null=True),
        ),
    ]
