# Generated by Django 5.1.7 on 2025-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
