# Generated by Django 5.1.7 on 2025-04-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='base.teacher'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
