# Generated by Django 5.1.7 on 2025-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attended_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
    ]
