# Generated by Django 5.1.7 on 2025-04-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attended_classes',
        ),
    ]
