# Generated by Django 5.1.7 on 2025-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_student_attended_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='total_classes',
            new_name='present_days',
        ),
        migrations.AddField(
            model_name='student',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
